spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wecat_dinner?characterEnconding=utf-8&useSSL=false
  jpa:
    show-sql: false
  redis:
    host: localhost
    database: 0
    port: 6379
    password:


server:
  context-path: /sell







